CREATE OR REPLACE TRIGGER ADD_REVIEW
AFTER INSERT
ON RATES
FOR EACH ROW
DECLARE
BEGIN
    UPDATE BOOK SET STAR = STAR + :NEW.STARS, REVIEW_COUNT = REVIEW_COUNT + 1
    WHERE ID = :NEW.BOOK_ID;

    -- Log the trigger call
    LOG_PROCEDURE_CALL('ADD_REVIEW', 'TRIGGER', NULL, 'NEW.STARS: ' || TO_CHAR(:NEW.STARS) || ', BOOK_ID: ' || TO_CHAR(:NEW.BOOK_ID));
END;
/


CREATE OR REPLACE TRIGGER UPDATE_REVIEW
AFTER UPDATE
OF STARS
ON RATES
FOR EACH ROW
DECLARE
BEGIN
    UPDATE BOOK SET STAR = STAR + (:NEW.STARS - :OLD.STARS)
    WHERE ID = :NEW.BOOK_ID;

    -- Log the trigger call
    LOG_PROCEDURE_CALL('UPDATE_REVIEW', 'TRIGGER', NULL, 'NEW.STARS: ' || TO_CHAR(:NEW.STARS) || ', OLD.STARS: ' || TO_CHAR(:OLD.STARS) || ', BOOK_ID: ' || TO_CHAR(:NEW.BOOK_ID));
END;
/


CREATE OR REPLACE TRIGGER UPDATE_STOCK
AFTER INSERT
ON BOOK_ORDER
FOR EACH ROW
DECLARE
    cartID NUMBER;
BEGIN
    cartID := :NEW.CART_ID;

    FOR R IN (SELECT * FROM PICKED WHERE CART_ID = cartID) 
    LOOP
        UPDATE BOOK SET STOCK = STOCK - R.AMOUNT WHERE ID = R.BOOK_ID;
    END LOOP;

    -- Log the trigger call
    LOG_PROCEDURE_CALL('UPDATE_STOCK', 'TRIGGER', NULL, 'NEW.CART_ID: ' || TO_CHAR(:NEW.CART_ID));
END;
/


CREATE OR REPLACE TRIGGER INCREASE_FOLLOWERS_OF_AUTHOR
AFTER INSERT
ON FOLLOW_AUTHOR
FOR EACH ROW
DECLARE
BEGIN
    UPDATE AUTHOR SET FOLLOWERS = FOLLOWERS + 1 
    WHERE ID = :NEW.AUTHOR_ID;

    -- Log the trigger call
    LOG_PROCEDURE_CALL('INCREASE_FOLLOWERS_OF_AUTHOR', 'TRIGGER', NULL, 'NEW.AUTHOR_ID: ' || TO_CHAR(:NEW.AUTHOR_ID));
END;
/


CREATE OR REPLACE TRIGGER DECREASE_FOLLOWERS_OF_AUTHOR
AFTER DELETE
ON FOLLOW_AUTHOR
FOR EACH ROW
DECLARE
BEGIN
    UPDATE AUTHOR SET FOLLOWERS = FOLLOWERS - 1 
    WHERE ID = :OLD.AUTHOR_ID;

    -- Log the trigger call
    LOG_PROCEDURE_CALL('DECREASE_FOLLOWERS_OF_AUTHOR', 'TRIGGER', NULL, 'OLD.AUTHOR_ID: ' || TO_CHAR(:OLD.AUTHOR_ID));
END;
/


CREATE OR REPLACE TRIGGER INCREASE_FOLLOWERS_OF_PUBLISHER
AFTER INSERT
ON FOLLOW_PUBLISHER
FOR EACH ROW
DECLARE
BEGIN
    UPDATE PUBLISHER SET FOLLOWERS = FOLLOWERS + 1 
    WHERE ID = :NEW.PUBLISHER_ID;

    -- Log the trigger call
    LOG_PROCEDURE_CALL('INCREASE_FOLLOWERS_OF_PUBLISHER', 'TRIGGER', NULL, 'NEW.PUBLISHER_ID: ' || TO_CHAR(:NEW.PUBLISHER_ID));
END;
/


CREATE OR REPLACE TRIGGER DECREASE_FOLLOWERS_OF_PUBLISHER
AFTER DELETE
ON FOLLOW_PUBLISHER
FOR EACH ROW
DECLARE
BEGIN
    UPDATE PUBLISHER SET FOLLOWERS = FOLLOWERS - 1 
    WHERE ID = :OLD.PUBLISHER_ID;

    -- Log the trigger call
    LOG_PROCEDURE_CALL('DECREASE_FOLLOWERS_OF_PUBLISHER', 'TRIGGER', NULL, 'OLD.PUBLISHER_ID: ' || TO_CHAR(:OLD.PUBLISHER_ID));
END;
/
