--Table for Book
create TABLE book(
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY ,
    author_id           NUMBER,
    publisher_id        NUMBER,
    NAME                VARCHAR2(100),
    IMAGE               varchar2(1000) default 'https://st2.depositphotos.com/5703046/12114/i/950/depositphotos_121142344-stock-photo-white-book-on-white-background.jpg',
    ISBN                VARCHAR2(100),
    PAGE                NUMBER,
    EDITION             VARCHAR2(100),
    publishing_year     NUMBER,
    Price               NUMBER,
    Stock               NUMBER,
    Language            VARCHAR2(20),
    GENRE               VARCHAR2(512),
    SUMMARY             VARCHAR2(3000),
    STAR                NUMBER default 0,
    REVIEW_COUNT        NUMBER default 0,
    CONSTRAINT book_pk PRIMARY KEY (ID),
    CONSTRAINT book_author_fk FOREIGN KEY(author_id) REFERENCES author(ID),
    CONSTRAINT book_publisher_fk FOREIGN KEY(publisher_id) REFERENCES publisher(ID)
);

--Table for Author
create TABLE author (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY ,
    Name        VARCHAR2(100),
    password    VARCHAR2(1024),
    IMAGE       varchar2(1000) default 'https://www.123rf.com/photo_91832679_man-avatar-icon-flat-illustration-of-man-avatar-vector-icon-isolated-on-white-background.html',
    DESCRIPTION VARCHAR2(3000),
    CONSTRAINT author_pk primary key (ID)
);

--Table for Publisher
create TABLE publisher(
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY ,
    name            VARCHAR2(100) NOT NULL,
    founding_date   DATE,
    IMAGE           VARCHAR2(1000) default 'https://ds.rokomari.store/rokomari110/company/publisher.png',
    CONSTRAINT publisher_pk PRIMARY KEY(ID)
);

--Table for User
create TABLE app_user (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY ,
    Name        VARCHAR2(100) NOT NULL ,
    EMAIL       varchar2(100) not null,
    password    VARCHAR2(1024) NOT NULL ,
    address     VARCHAR2(1000),
    PHONE       varchar2(20),
    DOB         varchar2(20),
    IMAGE       VARCHAR2(1000) default '/images/no-profile-picture.jpg',
    CONSTRAINT user_pk primary key (ID)
);


--Table for Voucher
create TABLE voucher (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY ,
    name        VARCHAR2(100) NOT NULL ,
    discount    NUMBER NOT NULL,
    validity    DATE,
    CAP         NUMBER default 250,
    CONSTRAINT voucher_pk PRIMARY KEY(ID)
);

--Table for Cart
create TABLE cart (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY ,
    user_id     NUMBER,
    created_at  DATE DEFAULT SYSDATE,
    CONSTRAINT cart_pk PRIMARY KEY(ID),
    CONSTRAINT cart_user_fk FOREIGN KEY(user_id) REFERENCES app_user(ID)
);

--Table for ordered book
create TABLE book_order (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cart_id         NUMBER,
    voucher_id      NUMBER,
    NAME            VARCHAR2(100) not null,
	phone1          VARCHAR2(20) not null,
	phone2          VARCHAR2(20),
	address         VARCHAR2(1000),
	pick            NUMBER default 1 not null,
    total_price     NUMBER,
    total_item      NUMBER,
    state           VARCHAR2(50),
    payment_method  VARCHAR2(50),
    created_at      DATE DEFAULT SYSDATE,
    CONSTRAINT order_pk PRIMARY KEY(ID),
    CONSTRAINT order_cart_fk FOREIGN KEY(cart_id) REFERENCES cart(ID),
    CONSTRAINT order_voucher_fk FOREIGN KEY(voucher_id) REFERENCES voucher(ID)
);

--Table for Review
create TABLE rates(
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY ,
    user_id     NUMBER,
    book_id     NUMBER,
    stars       NUMBER,
    REVIEW      VARCHAR2(1000),
    created_at  DATE DEFAULT SYSDATE,
    CONSTRAINT rates_pk PRIMARY KEY(ID),
    CONSTRAINT rates_user_fk FOREIGN KEY(user_id) REFERENCES app_user(ID),
    CONSTRAINT rates_book_fk FOREIGN KEY(book_id) REFERENCES book(ID)
);

--Table for picked book
create TABLE picked(
    ID         NUMBER GENERATED BY DEFAULT AS IDENTITY ,
    cart_id    NUMBER,
    book_id    NUMBER,
    created_at DATE DEFAULT SYSDATE,
    AMOUNT     NUMBER default 1,
    CONSTRAINT picked_pk PRIMARY KEY (ID),
    CONSTRAINT picked_cart_fk FOREIGN KEY (cart_id) REFERENCES cart(ID),
    CONSTRAINT picked_book_fk FOREIGN KEY (book_id) REFERENCES book (ID),
    CONSTRAINT PICKED_AMOUNT_MIN_MAX_VALUE check(AMOUNT between 1 and 5)
);

--Table for Wish List
create TABLE WISH_LIST(
	user_id INTEGER NOT NULL,
	book_id INTEGER NOT NULL,
	CONSTRAINT WISH_LIST_PK PRIMARY KEY(user_id,book_id),
	CONSTRAINT WISH_LIST_USER_FK FOREIGN KEY(user_id) REFERENCES APP_USER(ID) ,
	CONSTRAINT WISH_LIST_BOOK_FK FOREIGN KEY(book_id) REFERENCES BOOK(ID)
);



--Changed user table
alter table APP_USER
	add cart_id NUMBER
	add constraint APP_USER_CART_ID_FK foreign key(cart_id) references CART;






-- INSERT USER DATA

INSERT INTO C##APURBO.APP_USER (ID, NAME, PASSWORD, ADDRESS, EMAIL, CART_ID, IMAGE, DOB, PHONE) VALUES (21, 'SIZAN', '$2b$08$PSyjwxvcW53OZ/whRpRW.eI7G2w9CnLU/xJ1VQOUlCgrvxfGlOhzW', 'user.address', 'somethingelse@gmail.com', null, '/images/no-profile-picture.jpg', null, null);
INSERT INTO C##APURBO.APP_USER (ID, NAME, PASSWORD, ADDRESS, EMAIL, CART_ID, IMAGE, DOB, PHONE) VALUES (41, 'APURBO', '$2b$08$xnuPq9ALDxEqf/MzFGytXe00DiCKAnEGdT2/jBuWeZk6CjudCgBT2', 'user.address', 'tabassum@gmail.com', null, 'https://static.vecteezy.com/system/resources/previews/002/075/608/original/cute-bunny-and-butterfly-cartoon-animal-illustration-vector.jpg', '2007-09-13', '123456');

-- INSERT author data 

INSERT INTO C##APURBO.AUTHOR (ID, NAME, PASSWORD, IMAGE, DESCRIPTION) VALUES (3860, 'শাহাদুজ্জামান', '123456', 'https://ds.rokomari.store/rokomari110/people/5c69de634_2392.jpg', 'সমসাময়িক বাংলা কথাসাহিত্যে মননশীল সাহিত্যিক হিসেবে শাহাদুজ্জামানের অবস্থান অনন্য ও অগ্রণী। গল্প, উপন্যাসেই বেশি পরিচিত হলেও শাহাদুজ্জামানের উল্লেখযোগ্য কাজ রয়েছে প্রবন্ধ, অনুবাদ, ভ্রমণ এবং গবেষণার ক্ষেত্রেও। লেখকের মতে, তিনি আল বেরুনীর মতো দীর্ঘ নয়, বরং বিস্তৃত জীবনের আকাঙ্ক্ষা করেন। ১৯৬০ সালে ঢাকায় জন্মগ্রহণ করেন কথাশিল্পী শাহাদুজ্জামান। মাধ্যমিক ও উচ্চ মাধ্যমিক পর্যায়ের পড়াশোনা শেষ করেন মির্জাপুর ক্যাডেট কলেজ থেকে। এরপর চট্টগ্রাম মেডিকেল কলেজ থেকে পাস করে চিকিৎসক হিসেবে কাজ করেছেন উন্নয়ন সংস্থা ব্র্যাকের গ্রামীণ স্বাস্থ্য প্রকল্পে। উচ্চতর শিক্ষার জন্য পরবর্তীতে জনস্বাস্থ্য বিষয়ে ঢাকা বিশ্ববিদ্যালয় থেকে স্নাতকোত্তর এবং নেদারল্যান্ডসের আমস্টার্ডাম বিশ্ববিদ্যালয় থেকে চিকিৎসা নৃবিজ্ঞানে পিএইচডি ডিগ্রি অর্জন করেন।');
INSERT INTO C##APURBO.AUTHOR (ID, NAME, PASSWORD, IMAGE, DESCRIPTION) VALUES (210, 'মাহবুবুর রহমান', '123456', 'https://ds.rokomari.store/rokomari110/people/7546564f7_4881.jpg', 'বাংলা ভাষায় আইসিটি বিষয়ক প্রকাশনার অগ্রদূত মাহবুবুর রহমান, এ পর্যন্ত বই লিখেছেন ১০৮টি। বাংলাদেশে তিনিই একমাত্র ব্যক্তি যিনি ১৯৯২ সাল থেকে নিবেদিতভাবে তথ্য প্রযুক্তির বিভিন্ন বিষয়ে লিখে চলেছেন। দেশে তথ্য প্রযুক্তির ক্ষেত্রে বিশেষ অবদান এবং বিভিন্ন সামাজিক ও সাংস্কৃতিক সংগঠক হিসেবে আমেরিকান বায়োগ্রাফিক্যাল ইন্সটিটিউট কর্তৃক ‘ওয়ার্ল্ড হুজ হু’ এর নবম সংস্করণে তাঁর জীবনী প্রকাশিত হয়েছে। তাঁর লেখা বই বাংলাদেশ ও পশ্চিমবঙ্গ ছাড়াও বিশ্বের বিভিন্ন দেশে অবস্থানরত বাংলা ভাষাভাষীদের মাঝে ব্যাপক জনপ্রিয়তা পেয়েছে। বর্তমানে তিনি মালয়েশিয়ার বিখ্যাত পাবলিক প্রযুক্তি বিশ্ববিদ্যালয় ইউনিভার্সিটি মালয়েশিয়া পাহাং (ইউএমপি)-তে পিএইচডি গবেষক হিসেবে কাজ করছেন।');
INSERT INTO C##APURBO.AUTHOR (ID, NAME, PASSWORD, IMAGE, DESCRIPTION) VALUES (210, 'মাহবুবুর রহমান', '123456', 'https://ds.rokomari.store/rokomari110/people/7546564f7_4881.jpg', 'বাংলা ভাষায় আইসিটি বিষয়ক প্রকাশনার অগ্রদূত মাহবুবুর রহমান, এ পর্যন্ত বই লিখেছেন ১০৮টি। বাংলাদেশে তিনিই একমাত্র ব্যক্তি যিনি ১৯৯২ সাল থেকে নিবেদিতভাবে তথ্য প্রযুক্তির বিভিন্ন বিষয়ে লিখে চলেছেন। দেশে তথ্য প্রযুক্তির ক্ষেত্রে বিশেষ অবদান এবং বিভিন্ন সামাজিক ও সাংস্কৃতিক সংগঠক হিসেবে আমেরিকান বায়োগ্রাফিক্যাল ইন্সটিটিউট কর্তৃক ‘ওয়ার্ল্ড হুজ হু’ এর নবম সংস্করণে তাঁর জীবনী প্রকাশিত হয়েছে। তাঁর লেখা বই বাংলাদেশ ও পশ্চিমবঙ্গ ছাড়াও বিশ্বের বিভিন্ন দেশে অবস্থানরত বাংলা ভাষাভাষীদের মাঝে ব্যাপক জনপ্রিয়তা পেয়েছে। বর্তমানে তিনি মালয়েশিয়ার বিখ্যাত পাবলিক প্রযুক্তি বিশ্ববিদ্যালয় ইউনিভার্সিটি মালয়েশিয়া পাহাং (ইউএমপি)-তে পিএইচডি গবেষক হিসেবে কাজ করছেন।');

-- INSERT publisher data

INSERT INTO C##APURBO.PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (531, 'Bloomsbury Publishing', null, 'https://media-exp1.licdn.com/dms/image/C4E0BAQEDkPybVXr47Q/company-logo_200_200/0/1544531682586?e=2159024400&v=beta&t=JjAs9ok_PwgXA9CFsXKm3bt6fjbFI4N7SZRn4ajOUVg');
INSERT INTO C##APURBO.PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (102, 'Palok Publishers', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO C##APURBO.PUBLISHER (ID, NAME, FOUNDING_DATE, IMAGE) VALUES (105, 'গদ্যপদ্য', null, 'https://ds.rokomari.store/rokomari110/company/publisher.png');


--INSERT book data 
INSERT INTO C##APURBO.BOOK (ID, AUTHOR_ID, PUBLISHER_ID, PUBLISHING_YEAR, PRICE, STOCK, LANGUAGE, IMAGE, NAME, ISBN, PAGE, EDITION, SUMMARY, GENRE, STAR, REVIEW_COUNT) VALUES (190, 3860, 531, null, 450, 0, 'Bangla', '/images/books/defaultbook.jpg', 'নূরজাহান ১ম পর্ব', '9847010503746', 286, '4th Print, 2015', null, 'সমকালীন উপন্যাস', 0, 0);
INSERT INTO C##APURBO.BOOK (ID, AUTHOR_ID, PUBLISHER_ID, PUBLISHING_YEAR, PRICE, STOCK, LANGUAGE, IMAGE, NAME, ISBN, PAGE, EDITION, SUMMARY, GENRE, STAR, REVIEW_COUNT) VALUES (146, 3860, 531, null, 250, 30, 'Bangla', '/images/books/defaultbook.jpg', 'মায়াঘর', '9789849099109', 136, '3rd Print, 2014', null, 'সমকালীন গল্প', 0, 0);
INSERT INTO C##APURBO.BOOK (ID, AUTHOR_ID, PUBLISHER_ID, PUBLISHING_YEAR, PRICE, STOCK, LANGUAGE, IMAGE, NAME, ISBN, PAGE, EDITION, SUMMARY, GENRE, STAR, REVIEW_COUNT) VALUES (147, 3860, 531, null, 400, 100, 'Bangla', '/images/books/defaultbook.jpg', 'সমগ্র কিশোর উপন্যাস-২', '9789849132929', 255, '1st, 2015', null, 'শিশু-কিশোর রচনা সমগ্র', 0, 0);
