CREATE OR REPLACE PROCEDURE ASSIGN_CART_TO_USER(
    USERID IN NUMBER 
) 
IS 
    CARTID NUMBER;
BEGIN 
    INSERT INTO CART(USER_ID) VALUES(USERID) RETURNING ID INTO CARTID;
    
    UPDATE APP_USER SET CART_ID = CARTID WHERE ID = USERID;
END;
