

CREATE OR REPLACE TRIGGER ADD_REVIEW
AFTER INSERT
ON RATES
FOR EACH ROW
DECLARE

BEGIN
    UPDATE BOOK SET STAR = STAR + :NEW.STARS,REVIEW_COUNT = REVIEW_COUNT+1
    WHERE ID = :NEW.BOOK_ID;
end;



CREATE OR REPLACE TRIGGER UPDATE_REVIEW
AFTER UPDATE
OF STARS
ON RATES
FOR EACH ROW
DECLARE

BEGIN
    UPDATE BOOK SET STAR = STAR + (:NEW.STARS-:OLD.STARS)
    WHERE ID = :NEW.BOOK_ID;
end;



CREATE OR REPLACE TRIGGER ADD_CART 
AFTER INSERT 
ON USER 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO CART (USER_ID) VALUES (:NEW.ID);
END;