CREATE OR REPLACE TRIGGER ADD_REVIEW
AFTER INSERT
ON RATES
FOR EACH ROW
DECLARE

BEGIN
    UPDATE BOOK SET STAR = STAR + :NEW.STARS,REVIEW_COUNT = REVIEW_COUNT+1
    WHERE ID = :NEW.BOOK_ID;
end;



CREATE OR REPLACE TRIGGER UPDATE_REVIEW
AFTER UPDATE
OF STARS
ON RATES
FOR EACH ROW
DECLARE

BEGIN
    UPDATE BOOK SET STAR = STAR + (:NEW.STARS-:OLD.STARS)
    WHERE ID = :NEW.BOOK_ID;
end;



CREATE OR REPLACE TRIGGER ASSIGN_CART_AFTER_ORDER
AFTER INSERT ON BOOK_ORDER
FOR EACH ROW 
DECLARE
    USERID NUMBER;
BEGIN 

    SELECT USER_ID INTO USERID  FROM CART WHERE CART_ID = :NEW.CART_ID;

    ASSIGN_CART_TO_USER(USERID);
END;